### PR TITLE
Fix voice channel limit colors

### PR DESCRIPTION
**Pull request by shirokoneko**
This PR just fixes voice channel limit colors not appearing on Kyanite as seen below
music

### CODE REVIEW

**Comment by Aely0** [comment]
In addition to updating outdated selectors, we should also switch to the root color palette.

My suggestion would be something like:
- `hover-dark-color` for `users`
- `hover-color` for `total`
- `rgba(0, 0, 0, 0.55)` for `total:after` (for decent element blending)
- and finally `soft-bright-color` as the text color for that whole element wrapper

However, feel free to play around with the look if you wish, with the root color palette in mind of course.

**Comment by shirokoneko** [comment]
I've also noticed some elements have yet to be colored (e.g. inside of server folders, community settings menus, some elements of Nitro/boosting screens).

If you want, I could probably theme those too.

**Comment by Aely0** [comment]
I try to have most things covered, though with time, some things break and stay unnoticed as there are features/menus I do not use or see regularly within my daily use of Discord. If you come up on such cases for more tucked away UI elements having the default look, feel free to theme them, or at least point them out to me. Either way, any help is appreciated!

**Comment by Aely0** [comment]
In either case, thanks! I've looked over the things you've mentioned and I'll get it sorted right now actually, as they seem like quick and straight forward fixes.

**Comment by Aely0** [comment]
Ok, I think I got everything, that I could find at least. Let me know if there's still something missing.

**Comment by shirokoneko** [comment]
Hi, I don't really have much time right now but I've managed to try it out for a bit. Here's my feedback:
- While I like the themed server folders, it kinda sucks that my custom folder colors aren't used. I'm pretty sure it's to avoid inconsistency or something, but I would love to have my custom colors back.
- Some areas still aren't themed, for example: Community server settings, nitro (boost) tab, etc.:
DiscordCanary_6lvIyEIJLj
DiscordCanary_sHi8wJDppM
- Text colors on certain areas (hypesquad houses for example) look off
DiscordCanary_qwHOOz8TuT
- Might be just a personal preference, but I don't like how the emote size are shrunken to the old 32px size. I prefer it how it is now so I've made some changes on my end for that.
- I've noticed the quick action bar is removed from this theme. (It's also unthemed as well). Don't know why, but I've added it back on my own fork
DiscordDevelopment_L7rgPo386U
- Sometimes I've had trouble trying to select the right message to right-click or react on. Perhaps maybe add the message highlight-on-hover back, perhaps as a translucent color over it using the hover-color?
- You've made it so message text color is white with an `!important` flag set to it. If you recall the Discord outage from last week, I didn't realize my messages failed to send because they didn't turn red. I'll be making a PR for that since I've already done that so it's easier for people who use Kyanite to see that their messages failed to send.

**Pull request merged**
